# Paths
DATA_PATH: data/yamaha_v0/
SAVE_MODEL_PATH: runs/model_v0.6.pt # Comment this out to autoname models
LOAD_MODEL_PATH: runs/mobilenetv3large_v1.50.pt

# Image resize variables
IMG_HEIGHT: 224
IMG_WIDTH: 224

# Hyperparameters
NUM_EPOCHS: 60
NUM_MASK_CHANNELS: 8
BATCH_SIZE: 2
LEARNING_RATE: 0.0004
IS_INCEPTION: true
BACKBONE: resnet101 # mobilenetv3large, resnet50, resnet101